import { defineConfig, type Plugin } from 'vite';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

function fnv1a(str: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36);
}

const SW_TEMPLATE = `// RACE2 offline shell — generated by vite build; edit the template in vite.config.ts instead.
const CACHE = 'race2-__CACHE_HASH__';
const PRECACHE = __ASSETS__;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(PRECACHE.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'no-store' });
        if (res && (res.ok || res.type === 'opaque')) await cache.put(url, res);
        else console.warn('[sw] precache non-ok', url, res && res.status);
      } catch (err) {
        console.warn('[sw] precache failed', url, err);
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.headers.has('range')) return;
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res && res.ok) {
          const cache = await caches.open(CACHE);
          await cache.put('./index.html', res.clone());
          await cache.put('./', res.clone());
        }
        return res;
      } catch {
        const cache = await caches.open(CACHE);
        return (
          (await cache.match('./index.html', { ignoreVary: true, ignoreSearch: true })) ||
          (await cache.match('./', { ignoreVary: true, ignoreSearch: true })) ||
          Response.error()
        );
      }
    })());
    return;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreVary: true, ignoreSearch: true });
    return hit || fetch(req);
  })());
});
`;

function race2ServiceWorker(): Plugin {
  return {
    name: 'race2-service-worker',
    apply: 'build',
    generateBundle(_, bundle) {
      const shell = ['manifest.webmanifest', 'icons/icon-192.png', 'icons/icon-512.png'];
      for (const f of shell) {
        if (!existsSync(fileURLToPath(new URL('./public/' + f, import.meta.url)))) {
          this.error('sw precache: missing public/' + f + ' — run `node scripts/make-icons.mjs`');
        }
      }
      const hashed = Object.keys(bundle)
        .filter((n) => n !== 'index.html' && n !== 'sw.js')
        .sort()
        .map((n) => './' + n);
      const list = ['./', './index.html', ...shell.map((f) => './' + f), ...hashed];
      const source = SW_TEMPLATE.replace('__CACHE_HASH__', fnv1a(list.join('\n'))).replace('__ASSETS__', JSON.stringify(list));
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: './',
  build: {
    target: 'es2022',
    chunkSizeWarningLimit: 1500,
  },
  plugins: [race2ServiceWorker()],
  server: { host: true },
});
